name: RestAssured API Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#  schedule:
#    - cron: 05 17 29 05 *
#    - cron: 07 17 29 05 *

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Allure Commandline
      uses: actions/setup-node@v3
    - run: npm install -g allure-commandline --save-dev

    - name: Run TestNG Suite
      run: mvn clean test -Dsuite=suite -X

    - name: Generate Allure Report
      run: |
        mkdir -p target/allure-report
        allure generate target/allure-results --clean -o target/allure-report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: allure-report
        path: target/allure-report

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: logs
        path: logs/

    - name: Publish TestNG XML Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
